name: Release

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.10.0
          registry-url: https://npm.pkg.github.com/
          scope: '@vestfi'
      - name: Set current organization as scope
        run: echo "@vestfi:registry=https://npm.pkg.github.com/" >> .npmrc
      - name: Set registry with token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACCESS_TOKEN }}" > .npmrc
      - run: npm install -g yarn
      - run: yarn install --ignore-scripts

  release:
    # Only release on push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # Waits for build jobs for each Node.js version to complete
    needs: [build]
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.10.0
          registry-url: https://npm.pkg.github.com/
          scope: '@vestfi'
      - name: Set current organization as scope
        run: echo "@vestfi:registry=https://npm.pkg.github.com/" >> .npmrc
      - name: Set registry with token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACCESS_TOKEN }}" > .npmrc
      - run: npm install -g yarn
      - run: yarn install --ignore-scripts
      - name: Install semantic-release extra plugins
        run: yarn add --ignore-scripts -D @semantic-release/changelog @semantic-release/git
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
