name: Release

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/
          scope: '@vestfi'
      - name: Set current organization as scope
        run: echo "@vestfi:registry=https://npm.pkg.github.com/" >> .npmrc
      - name: Set registry with token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACCESS_TOKEN }}" > .npmrc
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --ignore-scripts

  publish-gpr:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://npm.pkg.github.com/
          scope: '@vestfi'
      - name: Set current organization as scope
        run: echo "@vestfi:registry=https://npm.pkg.github.com/" >> .npmrc
      - name: Set registry with token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.ACCESS_TOKEN }}" > .npmrc
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install --ignore-scripts
      - run: npm version patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.ACCESS_TOKEN}}
